"""Fixed-template Testinfra test module generation."""

from __future__ import annotations

from pathlib import Path

from aegis_test_generator.test_templates.schemas import TestCase, TestPlan


class RendererError(Exception):
    """Failed to render or write generated tests."""

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_DEFAULT_OUTPUT = _REPO_ROOT / "outputs" / "generated_tests" / "generated_tests.py"

_MODULE_HEADER = (
    '# Generated by aegis_test_generator (fixed templates only; do not hand-edit).\n'
    '# noqa: asserts allowed — infra acceptance tests.\n'
    "\n\n"
)


def _path_lit(tc: TestCase) -> str:
    return repr(tc.target)


def _require_expected(tc: TestCase, label: str) -> str:
    if tc.expected is None:
        raise RendererError(f"test_type {tc.test_type!r} requires non-null expected ({label})")
    return repr(tc.expected)


def _comment(reason: str) -> str:
    one = reason.replace("\n", " ").replace("\r", "").strip()
    if len(one) > 240:
        one = one[:237] + "..."
    one = one.replace("#", "")
    return f"    # {one}\n"


def _func_body(tc: TestCase) -> str:
    p = _path_lit(tc)

    match tc.test_type:
        case "file_exists":
            return f"    f = host.file({p})\n    assert f.exists\n"
        case "file_absent":
            return f"    f = host.file({p})\n    assert not f.exists\n"
        case "directory_exists":
            return f"    d = host.file({p})\n    assert d.is_directory\n"
        case "package_installed":
            return f"    assert host.package({p}).is_installed\n"
        case "package_absent":
            return f"    assert not host.package({p}).is_installed\n"
        case "content_contains":
            needle = _require_expected(tc, "substring")
            return f"    assert {needle} in host.file({p}).content_string\n"
        case "content_not_contains":
            needle = _require_expected(tc, "substring")
            return f"    assert {needle} not in host.file({p}).content_string\n"
        case "content_changed":
            old_val = _require_expected(tc, "old content substring that must no longer appear")
            return (
                f"    f = host.file({p})\n"
                f"    assert f.exists\n"
                f"    assert {old_val} not in f.content_string\n"
            )
        case "file_mode":
            if tc.expected is None:
                raise RendererError(
                    "test_type 'file_mode' requires non-null expected (chmod-style mode string)"
                )
            raw_mode = str(tc.expected).strip().lower()
            # Accept "0755", "755", "0o755" → render as Python octal integer literal
            plain = raw_mode.replace("0o", "").lstrip("0") or "0"
            try:
                mode_int = int(plain, 8)
            except ValueError as exc:
                raise RendererError(
                    f"file_mode expected must be an octal mode string, got {tc.expected!r}"
                ) from exc
            octal_lit = f"0o{oct(mode_int)[2:]}"
            return f"    assert host.file({p}).mode == {octal_lit}\n"
        case "file_mode_changed":
            if tc.expected is None:
                raise RendererError(
                    "test_type 'file_mode_changed' requires 'expected' (new mode after patch)"
                )
            if tc.expected_before is None:
                raise RendererError(
                    "test_type 'file_mode_changed' requires 'expected_before' (old mode before patch)"
                )
            def _parse_mode(raw: object, label: str) -> str:
                s = str(raw).strip().lower().replace("0o", "").lstrip("0") or "0"
                try:
                    int(s, 8)
                except ValueError as exc:
                    raise RendererError(
                        f"file_mode_changed {label} must be an octal mode string, got {raw!r}"
                    ) from exc
                return f"0o{oct(int(s, 8))[2:]}"
            old_oct = _parse_mode(tc.expected_before, "expected_before")
            new_oct = _parse_mode(tc.expected, "expected")
            return (
                f"    f = host.file({p})\n"
                f"    assert f.mode != {old_oct}\n"
                f"    assert f.mode == {new_oct}\n"
            )
        case "file_owner":
            owner = _require_expected(tc, "owner user")
            return f"    assert host.file({p}).user == str({owner})\n"
        case "binary_executable":
            return (
                f"    f = host.file({p})\n"
                "    assert f.exists\n"
                "    assert f.is_file\n"
                "    assert f.is_executable\n"
            )
        case "command_succeeds":
            return f"    out = host.run({p})\n    assert out.rc == 0\n"
        case "service_running":
            return f"    assert host.service({p}).is_running\n"
        case "service_enabled":
            return f"    assert host.service({p}).is_enabled\n"
        case "port_listening":
            return f"    assert host.socket({p}).is_listening\n"
        case "user_exists":
            return f"    assert host.user({p}).exists\n"
        case "group_exists":
            return f"    assert host.group({p}).exists\n"
        case "symlink_exists":
            return f"    f = host.file({p})\n    assert f.exists\n    assert f.is_symlink\n"
        case "command_output_contains":
            needle = _require_expected(tc, "expected substring in stdout")
            return f"    out = host.run({p})\n    assert out.rc == 0\n    assert {needle} in out.stdout\n"
        case "package_version":
            ver = _require_expected(tc, "expected version string")
            return f"    pkg = host.package({p})\n    assert pkg.is_installed\n    assert pkg.version == {ver}\n"
        case "package_version_range":
            constraint = _require_expected(tc, "PEP-440 version specifier e.g. '>=2.0,<3.0'")
            return (
                f"    from packaging.specifiers import SpecifierSet\n"
                f"    pkg = host.package({p})\n"
                f"    assert pkg.is_installed\n"
                f"    assert pkg.version in SpecifierSet({constraint})\n"
            )
        case unknown:
            raise RendererError(f"unknown test_type: {unknown!r}")


def _render_function(index: int, tc: TestCase) -> str:
    name = f"test_{index}_{tc.test_type}"
    body = _func_body(tc)
    note = tc.reason or tc.test_type
    prefix = _comment(note)
    return f"def {name}(host):\n{prefix}{body}"


def render_plan(plan: TestPlan, output_path: Path | None = None) -> Path:
    """Write a Testinfra(pytest) module; return output path."""
    path = output_path if output_path is not None else _DEFAULT_OUTPUT

    chunks: list[str] = [_MODULE_HEADER]
    for i, tc in enumerate(plan.tests):
        chunks.append(_render_function(i, tc))
        chunks.append("\n\n")

    module_text = "".join(chunks).rstrip() + "\n"

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(module_text, encoding="utf-8")
    except OSError as exc:
        raise RendererError(f"cannot write generated tests to {path}: {exc}") from exc

    return path
