"""Tests for aegis_test_generator.test_templates.renderer."""

from __future__ import annotations

import ast
import re
from types import SimpleNamespace

import pytest

from aegis_test_generator.planner.llm_planner import SUPPORTED_TEST_TYPES
from aegis_test_generator.test_templates import render_plan
from aegis_test_generator.test_templates.renderer import RendererError, _func_body
from aegis_test_generator.test_templates.schemas import TestCase, TestPlan


def _row(test_type: str) -> dict:
    base = {"test_type": test_type, "target": "/example/target"}
    if test_type == "content_contains":
        base["expected"] = "needle"
    elif test_type == "content_not_contains":
        base["expected"] = "forbidden"
    elif test_type == "content_changed":
        base["expected"] = "old_value"
    elif test_type == "file_mode":
        base["target"] = "/etc/issue"
        base["expected"] = "644"
    elif test_type == "file_mode_changed":
        base["target"] = "/etc/issue"
        base["expected"] = "0600"
        base["expected_before"] = "0644"
    elif test_type == "file_owner":
        base["expected"] = "root"
    elif test_type == "port_listening":
        base["target"] = "tcp://0.0.0.0:80"
    elif test_type in ("user_exists", "group_exists"):
        base["target"] = "root"
    elif test_type == "command_output_contains":
        base["target"] = "echo hello"
        base["expected"] = "hello"
    elif test_type == "package_version":
        base["target"] = "curl"
        base["expected"] = "7.68.0"
    elif test_type == "package_version_range":
        base["target"] = "curl"
        base["expected"] = ">=7.0,<8.0"
    return base


def _full_plan() -> TestPlan:
    rows = [_row(tt) for tt in SUPPORTED_TEST_TYPES]
    return TestPlan(tests=[TestCase.model_validate(r) for r in rows])


def test_render_plan_all_types_parseable(tmp_path) -> None:
    plan = _full_plan()
    out = tmp_path / "nested" / "generated_tests.py"
    path = render_plan(plan, output_path=out)
    assert path == out
    assert out.exists()
    src = out.read_text(encoding="utf-8")
    assert "# Generated by aegis_test_generator" in src
    matches = list(re.finditer(r"^def test_\d+_", src, re.MULTILINE))
    assert len(matches) == len(SUPPORTED_TEST_TYPES)
    ast.parse(src)


def test_render_plan_one_function_named_per_case(tmp_path) -> None:
    plan = TestPlan(tests=[TestCase.model_validate({"test_type": "file_exists", "target": "/a"})])
    path = tmp_path / "generated_tests.py"
    render_plan(plan, output_path=path)
    lines = [
        ln
        for ln in path.read_text(encoding="utf-8").splitlines()
        if ln.startswith("def test_")
    ]
    assert lines == ["def test_0_file_exists(host):"]


def test_file_mode_requires_expected_renderer_error() -> None:
    tc = TestCase.model_validate({"test_type": "file_mode", "target": "/x"})
    with pytest.raises(RendererError):
        _func_body(tc)


def test_unknown_type_renderer_error_simple_namespace() -> None:
    bad = SimpleNamespace(test_type="__bad__", target="/", expected=None, reason=None)
    with pytest.raises(RendererError, match="unknown test_type"):
        _func_body(bad)


def test_content_contains_no_decode() -> None:
    tc = TestCase.model_validate(
        {"test_type": "content_contains", "target": "/etc/issue", "expected": "needle"}
    )
    body = _func_body(tc)
    assert "content_string" in body
    assert ".decode(" not in body


def test_content_not_contains_no_decode() -> None:
    tc = TestCase.model_validate(
        {"test_type": "content_not_contains", "target": "/etc/issue", "expected": "forbidden"}
    )
    body = _func_body(tc)
    assert "content_string" in body
    assert ".decode(" not in body
