# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # The playbook intends to install a package that does not exist.
    assert host.package('nonexistent-package-aegis-xyz-999').is_installed
