# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure git is installed as specified in the playbook.
    assert host.package('git').is_installed


def test_1_package_installed(host):
    # Ensure curl is installed as specified in the playbook.
    assert host.package('curl').is_installed


def test_2_directory_exists(host):
    # Ensure the aegis working directory is created.
    d = host.file('/opt/aegis')
    assert d.is_directory


def test_3_file_mode(host):
    # Ensure the aegis directory has the correct permissions.
    assert host.file('/opt/aegis').mode == 0o755


def test_4_file_owner(host):
    # Ensure the aegis directory is owned by root.
    assert host.file('/opt/aegis').user == str('root')


def test_5_file_exists(host):
    # Ensure the aegis config file is created.
    f = host.file('/opt/aegis/config.conf')
    assert f.exists


def test_6_content_contains(host):
    # Ensure the aegis config file contains the correct configuration.
    assert '[aegis]\nversion=1\nmode=strict' in host.file('/opt/aegis/config.conf').content_string


def test_7_content_not_contains(host):
    # Ensure the aegis config file does not contain any old configuration values.
    assert 'old_value' not in host.file('/opt/aegis/config.conf').content_string


def test_8_file_mode(host):
    # Ensure the aegis config file has the correct permissions.
    assert host.file('/opt/aegis/config.conf').mode == 0o644


def test_9_file_owner(host):
    # Ensure the aegis config file is owned by root.
    assert host.file('/opt/aegis/config.conf').user == str('root')
