# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure git is installed for version control operations.
    assert host.package('git').is_installed


def test_1_package_installed(host):
    # Ensure curl is installed for data transfer operations.
    assert host.package('curl').is_installed


def test_2_directory_exists(host):
    # Verify the aegis working directory is created.
    d = host.file('/opt/aegis')
    assert d.is_directory


def test_3_file_mode(host):
    # Ensure the aegis directory has the correct permissions.
    assert host.file('/opt/aegis').mode == '0755'


def test_4_file_owner(host):
    # Ensure the aegis directory is owned by root.
    assert host.file('/opt/aegis').user == str('root')


def test_5_file_exists(host):
    # Verify the aegis configuration file is created.
    f = host.file('/opt/aegis/config.conf')
    assert f.exists


def test_6_content_contains(host):
    # Ensure the aegis configuration file contains the aegis section.
    content = host.file('/opt/aegis/config.conf').content_string
    text = content.decode('utf-8', errors='replace')
    assert '[aegis]' in text


def test_7_content_contains(host):
    # Ensure the aegis configuration file specifies the correct version.
    content = host.file('/opt/aegis/config.conf').content_string
    text = content.decode('utf-8', errors='replace')
    assert 'version=1' in text


def test_8_content_contains(host):
    # Ensure the aegis configuration file specifies the strict mode.
    content = host.file('/opt/aegis/config.conf').content_string
    text = content.decode('utf-8', errors='replace')
    assert 'mode=strict' in text


def test_9_file_mode(host):
    # Ensure the aegis configuration file has the correct permissions.
    assert host.file('/opt/aegis/config.conf').mode == '0644'


def test_10_file_owner(host):
    # Ensure the aegis configuration file is owned by root.
    assert host.file('/opt/aegis/config.conf').user == str('root')
