# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure nginx is installed to serve web content.
    assert host.package('nginx').is_installed


def test_1_service_running(host):
    # Ensure nginx service is running to handle web requests.
    assert host.service('nginx').is_running
