# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure curl is installed as expected.
    assert host.package('curl').is_installed


def test_1_directory_exists(host):
    # Ensure the working directory is created.
    d = host.file('/opt/myapp')
    assert d.is_directory


def test_2_file_mode(host):
    # Ensure the working directory has the correct permissions.
    assert host.file('/opt/myapp').mode == 0o755


def test_3_package_absent(host):
    # The package does not exist and should not be installed.
    assert not host.package('nonexistent-package-aegis-xyz-999').is_installed


def test_4_file_absent(host):
    # The marker file should not be created as the previous task failed.
    f = host.file('/opt/myapp/ready')
    assert not f.exists
