# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure curl is installed as it is required for HTTP requests and data transfers.
    assert host.package('curl').is_installed
