# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # The playbook installs the curl package.
    assert host.package('curl').is_installed


def test_1_file_exists(host):
    # The curl binary should exist after installation.
    f = host.file('/usr/bin/curl')
    assert f.exists
