# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # The playbook attempts to install a package that does not exist. The test should verify that the package is not installed.
    assert host.package('nonexistent-package-aegis-xyz-999').is_installed
