# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure that the curl package is installed on all hosts.
    assert host.package('curl').is_installed
