# Generated by aegis_test_generator (fixed templates only; do not hand-edit).
# noqa: asserts allowed — infra acceptance tests.


def test_0_package_installed(host):
    # Ensure curl is installed
    assert host.package('curl').is_installed


def test_1_directory_exists(host):
    # Ensure the working directory is created
    d = host.file('/opt/myapp')
    assert d.is_directory


def test_2_file_mode(host):
    # Ensure the directory has the correct permissions
    assert host.file('/opt/myapp').mode == 0o755


def test_3_package_installed(host):
    # Attempt to install a non-existent package
    assert host.package('nonexistent-package-aegis-xyz-999').is_installed


def test_4_file_absent(host):
    # Marker file should not exist as the task never runs
    f = host.file('/opt/myapp/ready')
    assert not f.exists
